// GRO-407: VENDORED COPY. Source of truth lives in tickadoo/howard at
// src/quality/seasonal-variants.ts (commit 3371a75a6cd5d1d4fd9454b07d6643baca1ae64d).
// Do not edit this file directly. Run scripts/sync-quality.sh to refresh.
// CI sync-check in .github/workflows/quality-sync.yml fails if drift is detected.
// See src/shared/quality/SYNC.md for the full vendoring contract.

/**
 * Seasonal / variant title detection + review-count suppression.
 *
 * **Problem:** When a venue lists a seasonal or limited-time variant
 * (e.g. "Christmas at the London Eye", "Halloween Haunted Walking Tour",
 * "NYE at the Empire State Building"), the underlying supplier feed
 * frequently inherits the parent venue's aggregate `review_count` and
 * `rating` onto the variant row. The London Eye main attraction has
 * ~16,500 reviews; the 10-day Christmas variant gets the same 16,500
 * displayed against it. This is a user-visible falsehood.
 *
 * **Solution:** Pure title-based heuristic to detect seasonal/variant
 * titles. Surfaces (OpenAI feed, public MCP, @howard chatbot, future
 * feeds) call {@link shouldSuppressReviews} on every row before
 * surfacing review/rating fields. If the predicate returns true, the
 * surface emits empty/null for those fields.
 *
 * **History:**
 *   - GRO-405 (Tier 1.5): introduced `isSeasonalVariantTitle` +
 *     `formatRatingTuple` for the OpenAI feed
 *   - GRO-406 (Tier 1.6): fixed the wire to actually fire via call-site
 *     `row.name` parameter (silent squash-merge drop in PR #1033)
 *   - GRO-408 (this module): extracted to cross-surface module so the
 *     MCP and @howard can use the same predicate
 *
 * **Cross-surface use:**
 *   ```ts
 *   import { shouldSuppressReviews } from '@/quality';
 *
 *   // OpenAI feed
 *   if (shouldSuppressReviews(row.name, row.review_count)) {
 *     return { star_rating: '', review_count: '', popularity_score: '' };
 *   }
 *
 *   // Public MCP
 *   if (shouldSuppressReviews(row.name, row.review_count)) {
 *     experience.review_count = null;
 *     experience.rating = null;
 *   }
 *
 *   // @howard chatbot
 *   const showReviews = !shouldSuppressReviews(row.name, row.review_count);
 *   const prose = showReviews ? `(${row.review_count} reviews)` : '';
 *   ```
 *
 * @module quality/seasonal-variants
 */

/**
 * Regex patterns matching seasonal / limited-time / variant titles.
 *
 * Exported as readonly so callers can inspect for diagnostic UI but
 * cannot mutate the working set. Add new patterns here with a test in
 * `tests/quality.test.ts` that documents the title shape it's catching.
 */
export const VARIANT_TITLE_KEYWORDS: readonly RegExp[] = [
  /\b(?:christmas|xmas|hanukkah|diwali|easter|valentine'?s?)\b/i,
  /\b(?:halloween|spooky|haunted)\b/i,
  /\bnew\s+year'?s?(?:\s+eve)?\b/i,
  /\bnye\b/i,
  /\bsummer\s+(?:special|spectacular|edition)\b/i,
  /\b(?:late|after-hours)\s+(?:show|opening|tour)\b/i,
  /\b(?:fast[- ]?track|skip[- ]?the[- ]?line)\s+upgrade\b/i,
];

/**
 * True if the title matches any seasonal / variant keyword pattern.
 *
 * Used by {@link shouldSuppressReviews}. Exported in its own right
 * because some surfaces (analytics dashboards, supplier audits) want
 * to flag seasonal variants without applying the review-count gate.
 *
 * Pure function: no I/O, no env, no clock.
 */
export function isSeasonalVariantTitle(title: string): boolean {
  if (!title) return false;
  return VARIANT_TITLE_KEYWORDS.some((re) => re.test(title));
}

/**
 * Threshold above which a seasonal-variant row's review count is treated
 * as venue-inherited noise rather than offer-specific signal.
 *
 * Set to 500. Reasoning: a genuinely-reviewed seasonal pop-up will
 * accumulate dozens, occasionally low hundreds, of reviews over its
 * limited run. Counts above 500 on a 10-day Christmas event are
 * statistically implausible — they're almost always inherited from
 * the parent venue's evergreen aggregate.
 *
 * Exported so callers can compose richer logic (e.g. a "borderline"
 * UI affordance for rows just above the threshold).
 */
export const VENUE_INHERITED_REVIEW_THRESHOLD = 500;

/**
 * The cross-surface decision: should we suppress review/rating fields
 * for this row because the reviews are venue-inherited rather than
 * offer-specific?
 *
 * Returns true iff title matches a seasonal/variant pattern AND the
 * count exceeds {@link VENUE_INHERITED_REVIEW_THRESHOLD}.
 *
 * Each surface decides what "suppress" means in its formatting context:
 *   - OpenAI feed: emit empty string for review_count, star_rating, popularity_score
 *   - Public MCP: emit null for review_count and rating
 *   - @howard chatbot: omit the review tuple from prose entirely
 *
 * Pure function: no I/O, no env, no clock. Safe to call on every row
 * in a render path without performance concern (regex match against
 * 7 short patterns).
 */
export function shouldSuppressReviews(
  title: string | null | undefined,
  reviewCount: number | null | undefined,
): boolean {
  if (!title) return false;
  if ((reviewCount ?? 0) <= VENUE_INHERITED_REVIEW_THRESHOLD) return false;
  return isSeasonalVariantTitle(title);
}
