#!/usr/bin/env bash
# GRO-407: refresh vendored copies of howard/src/quality/* into src/shared/quality/.
# Run from the repo root. Requires GITHUB_TOKEN with read access to tickadoo/howard.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$REPO_ROOT"

if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "ERROR: GITHUB_TOKEN required." >&2
  exit 1
fi

VENDOR_DIR="src/shared/quality"
HOWARD_REPO="tickadoo/howard"
HOWARD_API="https://api.github.com/repos/$HOWARD_REPO"

# Currently vendored files (extend as src/quality/ grows under GRO-408)
FILES=("seasonal-variants.ts")

for f in "${FILES[@]}"; do
  echo "Refreshing $f from $HOWARD_REPO..."
  
  # Get current SHA from main
  SHA=$(curl -sS -H "Authorization: token $GITHUB_TOKEN" \
    "$HOWARD_API/contents/src/quality/$f?ref=main" \
    | python3 -c "import sys,json; print(json.load(sys.stdin)['sha'])")
  
  # Get raw content
  curl -sS -H "Authorization: token $GITHUB_TOKEN" -H "Accept: application/vnd.github.raw" \
    "$HOWARD_API/contents/src/quality/$f?ref=main" \
    -o "/tmp/howard-$f"
  
  # Prepend vendoring header
  cat > "$VENDOR_DIR/$f" <<HEADER
// GRO-407: VENDORED COPY. Source of truth lives in tickadoo/howard at
// src/quality/$f (commit $SHA).
// Do not edit this file directly. Run scripts/sync-quality.sh to refresh.
// CI sync-check in .github/workflows/quality-sync.yml fails if drift is detected.
// See src/shared/quality/SYNC.md for the full vendoring contract.

HEADER
  cat "/tmp/howard-$f" >> "$VENDOR_DIR/$f"
  rm "/tmp/howard-$f"
  echo "  ✓ $f synced (howard SHA: $SHA)"
done

echo ""
echo "Done. Commit the updated files with a message that names the howard SHA:"
echo "  git commit -m 'GRO-407: sync vendored quality helpers (howard SHA \\$SHA)'"
